CREATE TABLE IF NOT EXISTS PRODUCTS(
  PRODUCT_ID TEXT,
  PRODUCT_NAME TEXT,
  SUPPLIER_ID TEXT,
  CATEGORY_ID TEXT,
  UNIT TEXT,
  PRICE TEXT
);
INSERT INTO PRODUCTS(PRODUCT_ID,PRODUCT_NAME,SUPPLIER_ID,CATEGORY_ID,UNIT,PRICE)
VALUES
  ("1","CHAIS","1","1","10 BOXES*20 BAGS","18"),
  ("2","CHANG","1","1","24-12 OZ BOTTLES","19"),
  ("3","ANISEED SYRUP","1","2","12-550 ML BOTTLES","10"),
  ("4","CHEF ANTON SEASONING","2","2","48- 6 OZ JARS","22"),
  ("5","CHEF ANTON MIX","2","2","36 BOXES","21.35"),
  ("6","CHEF ANTON SEASONING","2","2","48- 6 OZ JARS","22"),
  ("7","CHEF ANTON MIX","2","2","36 BOXES","21.35");

SELECT COUNT(PRODUCT_ID)
FROM PRODUCTS;

SELECT AVG(Price)
FROM PRODUCTS;

SELECT SUM(Price)
FROM PRODUCTS; 


-----------------------------------------
CREATE TABLE IF NOT EXISTS NOBEL_WIN(
  YEAR TEXT,
  SUBJECT TEXT,
  WINNER TEXT,
  COUNTRY TEXT,
  CATEGORY TEXT
);
INSERT INTO NOBEL_WIN(YEAR,SUBJECT,WINNER,COUNTRY,CATEGORY)
VALUES
  ("1970","PHYSICS","HANNES ALFVEN","SWEDEN","SCIENTIST"),
  ("1970","PHYSICS","LOUIS NEEL","FRANCE","SCIENTIST"),
  ("1971","PHYSICS","PAUL","FRANCE","SCIENTIST"),
  ("1971","CHEMISTERY","HAMILTON","SWEDEN","LINGUIST"),
  ("1972","LITERATURE","BERNARD KELSON","GERMANY","ECONOMIST"),
  ("1972","ECONOMICS","JOSEPH","RUSSIA","ECONOMICS"),
  ("1973","BIOLOGY","PHILIPS","USA","PRIME MINISTER"),
  ("1980","BIOLOGY","MARTIN","USA","PRESIDENT"),
  ("1981","PHYSIOLOGY","HANNAH","HUNGARY","SCIENTIST"),
  ("1975","PHYSICS","PETER","CHILE","SCIENTIST");

SELECT * 
 FROM nobel_win 
  WHERE subject NOT LIKE 'P%' 
   ORDER BY year ASC, winner;


-- SELECT * 
--  FROM nobel_win 
--   WHERE subject NOT LIKE 'P%' 
--    ORDER BY year DESC, winner;