CREATE TABLE IF NOT EXISTS CLASS_ROSTER( RNO INT PRIMARY KEY NOT NULL, NAME TEXT NOT NULL, AGE INT DEFAULT(15), CONTACT INT NOT NULL);

INSERT INTO CLASS_ROSTER( RNO, NAME, AGE, CONTACT)
VALUES
                  (001, "CHAITANYA", 14, 5129202568),
                  (002, "AARUSHI",15 , 908023184),
                  (003, "DEVAM", 16, 089237409),
                  (004, "ALLEN", 17, 982034792),
                  (005, "CALLIE", 14, 80237498);

SELECT * from CLASS_ROSTER;

SELECT * from CLASS_ROSTER WHERE RNO>003;

SELECT * from CLASS_ROSTER WHERE NAME="CHAITANYA";

SELECT * from CLASS_ROSTER WHERE NAME="CHAITANYA" OR RNO<3;

SELECT * from CLASS_ROSTER WHERE NAME="CHAITANYA" AND RNO<3;

SELECT MIN(AGE) from CLASS_ROSTER ;


SELECT MAX(AGE) from CLASS_ROSTER ;
SELECT AVG(AGE) from CLASS_ROSTER ;


